image: python:3.6
test:
  stage: test
  script:
  - pip install pipenv
  - pipenv sync --dev
  - make jf/jsonlgen.so
  - pipenv run pytest jf --doctest-modules --cov --cov-report html
  - make test
  artifacts:
    paths:
    - coverage
    expire_in: 1 week
release:
  stage: deploy
  script:
  - pip install pipenv
  - pip install twine
  - pipenv sync --dev
  - make jf/jsonlgen.so
  - pipenv run python setup.py sdist build
  - twine upload dist/*
  artifacts:
    paths:
    - coverage
    expire_in: 1 week
  dependencies:
  - test
  only:
  - master
