image: python:3.6

test:
  stage: test
  script:
    - pip install -r test_requirements.txt
    - pip install -r requirements.txt
    - pip install .
    - make test
  artifacts:
    paths:
      - coverage
    expire_in: 1 week

pages:
  stage: deploy
  dependencies:
    - test
  script:
   - mkdir public
  artifacts:
    paths:
      - public
