py36_nose:
  image: python:3.6
  script:
    - pip install -r test_requirements.txt
    - pip install -r requirements.txt
    - pip install .
    - make test
  artifacts:
    paths:
      - coverage
    expire_in: 1 week
