sudo: false
language: python
python:
  - 3.5
addons:
  apt:
    packages:
    - apt-get install libpython-dev
install:
  - pip install -r requirements.txt
  - pip install codecov
script: make test
after_success: codecov
